# Use Python slim image
FROM python:3.12-slim

WORKDIR /app

# Copy and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy only E2E
COPY ./e2e ./e2e

# Comando for execute e2e tests
CMD ["pytest", "e2e", "--disable-warnings", "--maxfail=1", "-v", "--color=yes"]