FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./ ./tests

CMD ["sh", "-c", "pytest $TEST_PATH --disable-warnings --maxfail=1 -v --color=yes"]